# Some commonly used options have been documented as comments in this file.
# For advanced use and comprehensive documentation of the format, please see:
# https://docs.haskellstack.org/en/stable/yaml_configuration/

resolver: lts-20.17

packages:
- accelerate-llvm
- accelerate-llvm-native
- accelerate-llvm-ptx

extra-deps:
- github: tmcdonell/accelerate
  commit: b349b28e9bd9c0c6e0dd61481e4a037d08928e31

- github: llvm-hs/llvm-hs
  commit: 80e0de0f96eb78288c88fda0eaba0f7cf5d38a30  # llvm-15
  # commit: 423220bffac4990d019fc088c46c5f25310d5a33  # llvm-12
  subdirs:
    - llvm-hs
    - llvm-hs-pure

# Override default flag values for local packages and extra-deps
# flags: {}

# Extra per-package and global ghc options
# ghc-options:
#   llvm-hs: -optcxx=-std=c++14 -optcxx=-lstdc++ -optcxx=-fno-rtti

# Extra package databases containing global packages
# extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true
#
# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: ">=1.9"
#
# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64
#
# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
#
# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
#
# vim: nospell
