name: ci-macos

# Trigger the workflow on push or pull request
on:
  pull_request:
    # branches: [master]
  push:
    paths:
      - '.github/workflows/ci-macos.yml'
      - 'stack*.yaml'
      - '*/*.cabal'
      - '*/src/**'
      - '*/test/**'
      - '*/cbits/**'

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
      matrix:
        include:
          - ghc: "8.10"
            llvm: "9"

    env:
      STACK_FLAGS: "--fast --flag accelerate:nofib"

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.local/bin
          key: ${{ runner.os }}-local-bin-${{ matrix.ghc }}-${{ hashFiles('**.yaml') }}
          restore-keys: |
            ${{ runner.os }}-local-bin-${{ matrix.ghc }}

      - uses: actions/cache@v2
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-global-${{ matrix.ghc }}-${{ hashFiles('**.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-global-${{ matrix.ghc }}

      - uses: actions/cache@v2
        with:
          path: .stack-work
          key: ${{ runner.os }}-stack-local-${{ matrix.ghc }}-${{ hashFiles('**.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-local-${{ matrix.ghc }}

      - name: Install stack
        run: |
          mkdir -p ~/.local/bin
          if [[ ! -x ~/.local/bin/stack ]]; then
            brew install gnu-tar
            curl -sL https://get.haskellstack.org/stable/osx-x86_64.tar.gz | gtar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
            chmod a+x ~/.local/bin/stack
          fi
          echo "~/.local/bin" >> $GITHUB_PATH
          ln -s stack-${{ matrix.ghc }}.yaml stack.yaml

      - name: Install GHC
        run: |
          stack setup --install-ghc

      - name: Install LLVM
        run: |
          brew tap llvm-hs/homebrew-llvm
          brew install pkg-config libffi llvm-${{ matrix.llvm }}
          echo "PKG_CONFIG_PATH=$(brew --prefix)/opt/libffi/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV

      - name: Build dependencies
        run: |
          stack build $STACK_FLAGS --test --no-run-tests --only-dependencies

      - name: Build dependencies
        run: |
          stack build $STACK_FLAGS --test --no-run-tests --only-dependencies

      - name: Build accelerate-llvm
        run: |
          stack build accelerate-llvm $STACK_FLAGS --test --no-run-tests

      - name: Build accelerate-llvm-native
        run: |
          stack build accelerate-llvm-native $STACK_FLAGS --test --no-run-tests

      # - name: Build accelerate-llvm-ptx
      #   run: |
      #     stack build accelerate-llvm-ptx $STACK_FLAGS --test --no-run-tests

      - name: Test accelerate-llvm-native
        run: |
          stack test accelerate-llvm-native $STACK_FLAGS  --test-arguments='--hedgehog-tests=50 --hedgehog-shrinks=0 --timeout=120s --num-threads=1'

      - name: Test haddock generation
        run: |
          stack haddock --haddock --no-haddock-deps --no-haddock-hyperlink-source --haddock-arguments="--no-print-missing-docs" $STACK_FLAGS

